# Project: StudentScoreManager
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = STRUCT_ORGINAL.o STRUCT.o GPA.o
LINKOBJ  = STRUCT_ORGINAL.o STRUCT.o GPA.o
LIBS     = -L"D:/zips program files/Dev-Cpp/MinGW64/lib" -L"D:/zips program files/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/zips program files/Dev-Cpp/MinGW64/include" -I"D:/zips program files/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/zips program files/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/zips program files/Dev-Cpp/MinGW64/include" -I"D:/zips program files/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/zips program files/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/zips program files/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = StudentScoreManager.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

STRUCT_ORGINAL.o: STRUCT_ORGINAL.cpp
	$(CPP) -c STRUCT_ORGINAL.cpp -o STRUCT_ORGINAL.o $(CXXFLAGS)

STRUCT.o: STRUCT.cpp
	$(CPP) -c STRUCT.cpp -o STRUCT.o $(CXXFLAGS)

GPA.o: GPA.cpp
	$(CPP) -c GPA.cpp -o GPA.o $(CXXFLAGS)
